### PR TITLE
Optionally zip files at the end of jobs

### PR DESCRIPTION
**Pull request by gpetretto**
## Summary

Implementation for the option to tune the zip of files at the end of (vasp) Jobs, as discussed in #361.
3 options are available: zipping all the files, zipping only code specific files or no zipping at all. 

For vasp I gathered inputs and outputs from the links in #361, and added a few more that were not mentioned there. 

## TODO

* tests
* adding the option for other codes

### CODE REVIEW

**Comment by utf** [comment]
Thanks @gpetretto. I think this is a great change, but can you use the existing gzip functionality in `FileClient`? https://github.com/materialsproject/atomate2/blob/0955d70374b97704035917f98350bba1020cd9d9/src/atomate2/utils/file_client.py#L351

**Comment by utf** [comment]
Actually, one does not typically use the file client directly but instead the helper functions in `atomate2/common/files.py`. We already have a gunzip files function in there. But could you add a gzip_files function with a consistent set of arguments: https://github.com/materialsproject/atomate2/blob/0955d70374b97704035917f98350bba1020cd9d9/src/atomate2/common/files.py#L225

**Comment by gpetretto** [comment]
Thanks for pointing it out. Since it was originally using the monty gzip_dir I did not realize there was already an alternative in atomate2. Sorry. 

I tried to simply switch to `gzip_files`, but I incurred in an issue and I am not sure if this should be considered the expected behavior or a bug. I tried to pass my list of files to zip, but due to this part of the code 
https://github.com/materialsproject/atomate2/blob/0955d70374b97704035917f98350bba1020cd9d9/src/atomate2/common/files.py#L324-L326
the execution fails, as it still adds the files in the `include_files` list, even if they don't exist.
I am not sure in which case it would be useful to have the file in the list of filtered files, even when it does not exist. May I remove that `else` condition in `find_and_filter_files`?  Otherwise I will need to perform the check with glob before calling `gzip_files`.

**Comment by utf** [comment]
I believe you can just set allow_missing to True?

**Comment by utf** [comment]
> Otherwise I can add a test folder with a minimal set of files already unzipped.

I think this would be fine. Might be best to just `touch` the files, as their contents don't actually matter.

**Comment by gpetretto** [comment]
> I think this would be fine. Might be best to just `touch` the files, as their contents don't actually matter.

I don't think I can do that while making a standard test, since the mocked execution still parses the outputs. Is there already a way to bypass the parsing? A minimal working test seems to need at least real vasprun.xml, OUTCAR and CONTCAR files.

Otherwise an overall easier way would be to move this portion of the code:
https://github.com/materialsproject/atomate2/blob/5711de0db84eb34a1b71f3f9d646c9c399857811/src/atomate2/vasp/jobs/base.py#L223-L227
to a `zip_vasp_files` function and test it on its own.

**Comment by utf** [comment]
I see. I'm not sure of the best way to do it. Unless we add some additional logic to the tests for specifically checking the gzip status.

**Comment by gpetretto** [comment]
I tried to move the logic to a common function and test only its behavior. 
I also added the same option for Lobster and CP2K. 
For Lobster I followed @JaGeo's suggestion, but maybe it is better if she checks this.  
For CP2K I only added `cp2k.in` and `cp2k.out` in the list of files to zip. However, since I have little knowledge of CP2K and I don't know if there are other large files that need to be zipped in the folder, I left the default of the setting `CP2K_ZIP_FILES` to True. Is there anyone that should be pinged and could provide a better list of files for CP2K?

**Comment by utf** [comment]
I will merge this for now. Thanks very much @gpetretto

**Comment by 919607** [comment]
May I ask how to set the VASP file for compression? For example, if the WAVECAR is relatively large after calculation, I want to compress this file while not compressing the others

**Pull request merged**
