### PR TITLE
Lobster schema updates

### LINKED ISSUE #874: BUG: `pydantic` `UserWarning` from `LobsterTaskDocument`
@JaGeo @naik-aakash i get this warning from an unrelated atomate2 import

```py
from atomate2.vasp import powerups
>>> site-packages/pydantic/_internal/_fields.py:200: UserWarning: Field name "schema" in "LobsterTaskDocument" shadows an attribute in parent "StructureMetadata"
```

maybe it makes sense to rename the field anyway? `atomate2_version` seems like a more descriptive name

https://github.com/materialsproject/atomate2/blob/aee4be89b8a16a0f2a79e0c9aa22e3859826b4b9/src/atomate2/lobster/schemas.py#L725-L727

### PR DESCRIPTION
**Pull request by naik-aakash**
### Changes

1. Change field name `schema `to `atomate2_version `
2. Adapt `zpath `obtained via `monty `to work even with recent version of the monty package

### CODE REVIEW

**Comment by naik-aakash** [comment]
Hi @utf , this PR is ready for review / merged

**Comment by JaGeo** [comment]
@naik-aakash would this work on Windows? I guess not, right?

**Comment by naik-aakash** [comment]
> @naik-aakash would this work on Windows? I guess not, right?

I quickly ran the tests in atomate2 on a windows system, the schema test for LOBSTER works fine on windows as well, but the workflow ones fail but during zipping output step for VASP runs.

**Review by JaGeo — APPROVED** [review]

**Comment by JaGeo** [comment]
@naik-aakash thanks! I have merged this as this is a small change ;)

**Pull request merged**
