### PR TITLE
Add `m3gnet` support to Atomate2

### PR DESCRIPTION
**Pull request by matthewkuner**
## Summary

* Add `M3GNet` support from the [matgl repository](https://github.com/materialsvirtuallab/matgl) to Atomate2 forcefields.

## Additional dependencies introduced

* matgl

## Notes

* I do not plan to add support for MEGNet (as it seems to be inferior to M3GNet according to [matbench discovery](https://matbench-discovery.materialsproject.org/models)). Let me know if MEGNet has considerable demand too.

### CODE REVIEW

**Comment by matthewkuner** [comment]
I made a new `from_m3gnet_result` method in the `ForceFieldTaskDoc`. Currently, this is practically identical to the `from_chgnet_result` method; however, it does make it easier to adjust the methods in the future if they diverge.

**Comment by arosen93** [comment]
That was fast!!!

**Comment by matthewkuner** [comment]
> That was fast!!!
Kinda yes and kinda no. Most of this was honestly just copying and pasting from the CHGNet support. Not quite done yet either--seems like `Matgl` is in a state of flux right now, so I may let this sit for a bit

**Comment by matthewkuner** [comment]
@utf this should be ready for review. Let me know if the modified ForceFieldTaskDocument is satisfactory

**Comment by utf** [comment]
This looks perfect. Thank you.

**Comment by JaGeo** [comment]
Closes #379

**Pull request merged**
