### PR TITLE
Update to Pydantic v2

### PR DESCRIPTION
**Pull request by utf**
Final step in the MP ecosystem migration to `pydantic` v2! 🎉

### CODE REVIEW

**Comment by Andrew-S-Rosen** [comment]
For anything with `additional_fields` you also need to define the class with `extra="allow"` now btw.

**Comment by janosh** [comment]
@utf Tried to get this done but there are 26 failing tests left. Some unresolved references in there:

```
=========== 26 failed, 111 passed, 33 warnings in 443.86s (0:07:23) ============

ValueError: Could not resolve reference - fb0378b2-2600-4bf3-94cc-2d1eab3ec3d4 not in store or cache
```

**Comment by mjwen** [comment]
Was about the raise an issue... Glad that you are already working on this.

**Comment by utf** [comment]
Hi @Zhuoying @ardunn @hrushikesh-s, would one of you be able to take on this PR and try and get atomate2 compatible with pydantic2?

**Comment by hrushikesh-s** [comment]
Hi @utf,
While trying to resolve this PR, I'm encountering several cases (for eg, see [here](https://github.com/materialsproject/atomate2/blob/pydantic2/src/atomate2/cp2k/schemas/task.py#L406)) where Pydantic2 models are being instantiated with `incomplete class attributes`. This, in turn, leads to errors. Is there a recommended best practice within Pydantic2 for initializing a class when some of its attributes are missing, without the need to use the `Optional` class from the `typing` module?

**Comment by hrushikesh-s** [comment]
@janosh, thanks for letting me know! 

> Let me know if you can do the rest.

Yeah, I'll take care of the rest

**Comment by janosh** [comment]
@hrushikesh-s Interesting, we have 3 test failures here:

```
FAILED tests/common/test_jobs.py::test_retrieve_structure_from_materials_project - KeyError: '878c02e0-bde4-4a93-a5be-32088298965a'
FAILED tests/common/schemas/test_cclib.py::test_cclib_taskdoc - KeyError: 'test'
FAILED tests/vasp/flows/test_defect.py::test_formation_energy_maker - RuntimeError: Flow did not finish running successfully
============ 3 failed, 134 passed, 33 warnings in 441.98s (0:07:21) ============
```

Just to confirm, you only saw `test_formation_energy_maker` failing in #558?

**Comment by hrushikesh-s** [comment]
> @hrushikesh-s Interesting, we have 3 test failures here:
> 
> ```
> FAILED tests/common/test_jobs.py::test_retrieve_structure_from_materials_project - KeyError: '878c02e0-bde4-4a93-a5be-32088298965a'
> FAILED tests/common/schemas/test_cclib.py::test_cclib_taskdoc - KeyError: 'test'
> FAILED tests/vasp/flows/test_defect.py::test_formation_energy_maker - RuntimeError: Flow did not finish running successfully
> ============ 3 failed, 134 passed, 33 warnings in 441.98s (0:07:21) ============
> ```
> 
> Just to confirm, you only saw `test_formation_energy_maker` failing in #558?

Yeah, in #558 , only the `test_formation_energy_maker` was failing.

**Comment by hrushikesh-s** [comment]
> @hrushikesh-s Interesting, we have 3 test failures here:
> 
> ```
> FAILED tests/common/test_jobs.py::test_retrieve_structure_from_materials_project - KeyError: '878c02e0-bde4-4a93-a5be-32088298965a'
> FAILED tests/common/schemas/test_cclib.py::test_cclib_taskdoc - KeyError: 'test'
> FAILED tests/vasp/flows/test_defect.py::test_formation_energy_maker - RuntimeError: Flow did not finish running successfully
> ============ 3 failed, 134 passed, 33 warnings in 441.98s (0:07:21) ============
> ```
> 
> Just to confirm, you only saw `test_formation_energy_maker` failing in #558?

@janosh , I'm unable to replicate these `3 errors` in my local computer. I started from a new `conda` env, and installed `atomate2` from scratch and checked the status of the tests. I still get the same old single error that I got in #558 :
image
image

**Comment by janosh** [comment]
That's good to know! Maybe @utf can have another look at why CI is acting up. I have no leads.

**Comment by jmmshn** [comment]
@hrushikesh-s  made some changes to fix the defect test however there seems to be one remaining problem with emmet core:

```python
from emmet.core.tasks import TaskDoc
td = TaskDoc.from_directory("/Users/shen9/repos/mp/atomate2/tests/test_data/vasp/GaN_Mg_defect/bulk_relax/outputs")
print(td)
```
The `TaskDoc.entry` field is no longer populated autmatically when parsing.
I'm not sure how this was changed but something with knowledge about it can probably fix this relatively quick.

**Comment by jmmshn** [comment]
More context from the other PR:

> ## Fixing defect tests
> For #548 
> 
> Looks like the pydanctic2 PR is blocked by the defect formation energy test.
> 
> This fixes one of the problems:
> - The defect charge state sanity check requires the POTCAR data but we only have POTCAR spec so we cannot assign charge automatically.  Prior versions of atomate2 did not give a CI failure for this.  The particular job to check the charge state still failled but the CI is able to pass. 
> 
> But there seems to be a second problem that I'm not sure about:
> - The`bulk_summary["sc_entry"]` which comes directly from TaskDoc of the relaxation job now gives `None`
> Other fields for `bulk_summary` seems to be OK. 
> 
> ```python
>     relax_output: TaskDoc = relax_job.output
>     summary_d = {
>         "uc_structure": uc_structure,
>         "sc_entry": relax_output.entry,
>         "sc_struct": relax_output.structure,
> ```
> This creates the remaining error in the CI.  The strange thing here is that `relax_output.structure` is properly parsed but `relax_output.entry` is `None`.
>

**Comment by hrushikesh-s** [comment]
I recall @janosh and @munrojm recently made some changes to emmet to upgrade it from pydanticV1 to pydanticV2. Can one of you please take a look at this error?

**Comment by jmmshn** [comment]
Ok I did some more digging I think this has something to do with the validators trying to populate the `entry` attribute using `mode="after"` which is usually OK when you are just processing outputs but is problematic when you have a dynamic WF with a bunch of `Responses` that have not been populated yet. In pervious versions, we had `mode="before"` on the validators and that seemed to work but it was probably not actually checking this particular field.

**Comment by janosh** [comment]
@jmmshn Thanks for debugging this! Really appreciated since this transition is blocking several other PRs!

@munrojm I just did local testing. Turns out the failing defect test is fixed by just removing the `and self.task_id` on [this line](https://github.com/materialsproject/emmet/blob/4f2d9a007598d17acac569da04254618b3eade59/emmet-core/emmet/core/tasks.py#L409). Do we really need that?

**Comment by munrojm** [comment]
We can switch back to validating `before`, but will probably have to alter the validation function. I should be able to take care of this on the emmet side pretty easily.

**Comment by janosh** [comment]
This is turning into a nightmare. 😨 

@hrushikesh-s Could you take a look at this PR again? We're back to 32 failing tests after being down to 2 earlier. Maybe this came from updating `emmet-core` to v0.70.0. Not sure yet. But it's `pydantic` validation errors.

Also, `tests/common/schemas/test_cclib.py` is failing due to `MoleculeMetadata` in `emmet` [not accepting `additional_fields`](https://github.com/materialsproject/emmet/blob/f72d68d4f2ab88eef51e96ca3f261e63cca5c6d1/emmet-core/emmet/core/structure.py#L158) (needs `extra="allow")`. @munrojm I'll submit an `emmet` PR to fix that.

https://github.com/materialsproject/atomate2/blob/b5b9a2dc1d213f2a19b5d69b83e69a6602468654/tests/common/schemas/test_cclib.py#L91-L92

**Review by JaGeo — COMMENTED** [review]
We have a PR open that should fix this Lobster error 😬. Sorry!

**Comment by hrushikesh-s** [comment]
> This is turning into a nightmare. 😨
> 
> @hrushikesh-s Could you take a look at this PR again? We're back to 32 failing tests after being down to 2 earlier. Maybe this came from updating `emmet-core` to v0.70.0. Not sure yet. But it's `pydantic` validation errors.
> 
> Also, `tests/common/schemas/test_cclib.py` is failing due to `MoleculeMetadata` in `emmet` [not accepting `additional_fields`](https://github.com/materialsproject/emmet/blob/f72d68d4f2ab88eef51e96ca3f261e63cca5c6d1/emmet-core/emmet/core/structure.py#L158) (needs `extra="allow")`. @munrojm I'll submit an `emmet` PR to fix that.
> 
> https://github.com/materialsproject/atomate2/blob/b5b9a2dc1d213f2a19b5d69b83e69a6602468654/tests/common/schemas/test_cclib.py#L91-L92

@janosh, `135` tests are now passing in #565. The only test that's failing is `tests/common/schemas/test_cclib.py` due to the reason that you'd already identified. Fixing that error should **HOPEFULLY** make all the tests pass 🤓

**Comment by janosh** [comment]
@hrushikesh-s Looks like #565 didn't help. Still 32 failing tests here. Same validation errors as before. Very strange!

**Comment by hrushikesh-s** [comment]
@janosh, is it because `pydantic2` branch is `20 commits` behind `main` branch? Should we sync those 20 commits into pydantic2 and then I can retry to fix the unit test errors?
image

**Comment by janosh** [comment]
@hrushikesh-s Sure! But wasn't #565 behind as well?

**Comment by Zhuoying** [comment]
> @janosh, is it because `pydantic2` branch is `20 commits` behind `main` branch? Should we sync those 20 commits into pydantic2 and then I can retry to fix the unit test errors? image

Not for this reason, your PR did not include all commits here in #548.
@janosh I highly suspect 32 errors are from bump to emmet v0.70.0.

**Comment by janosh** [comment]
> @janosh I highly suspect 32 errors are from bump to emmet v0.70.0.

Me too. But we need emmet v0.70.0 since it contains the PR I submitted yesterday https://github.com/materialsproject/emmet/pull/853 that fixed the `entry=None` error in the `atomate2` defect workflow. @munrojm Is investigating afaik.

**Comment by hrushikesh-s** [comment]
> @hrushikesh-s Sure! But wasn't #565 behind as well?

> > @janosh, is it because `pydantic2` branch is `20 commits` behind `main` branch? Should we sync those 20 commits into pydantic2 and then I can retry to fix the unit test errors? image
> 
> @hrushikesh-s Not for this reason, your PR did not include all commits here in #548. @janosh I highly suspect 32 errors are from bump to emmet v0.70.0.

I've no idea why the CI is still failing. These same tests pass when I clone the pydantic2 branch (#566), and they also pass when I locally run the tests. Only exception is `test_cclib.py` which fails because of [this](https://github.com/materialsproject/atomate2/pull/548#issuecomment-1760090703)

**Comment by janosh** [comment]
> Only exception is `test_cclib.py` which fails because of [this](https://github.com/materialsproject/atomate2/pull/548#issuecomment-1760090703)

@hrushikesh-s Thanks for the reminder, forgot to push the fix for that. It's now up in https://github.com/materialsproject/emmet/pull/857. @munrojm Could you review?

**Comment by munrojm** [comment]
Yes I'll take a look very soon.

**Comment by Zhuoying** [comment]
@janosh Really weird, the CI tests failed here and passed in #567. 
Do you think we can directly merge that PR instead, or still wait for any potential fix from the emmet side?

**Comment by janosh** [comment]
@Zhuoying Those two branches are identical afaict so I don't understand how tests are failing here and passing there. Quite mysterious but I'm happy to merge #567 instead.

**Comment by Zhuoying** [comment]
@utf The fixes are merged in an identical PR (#567), so close this PR.

**Pull request closed without merging**
