### PR TITLE
[WIP] fixing errors in pydantic V2 implementation

### PR DESCRIPTION
**Pull request by hrushikesh-s**

### CODE REVIEW

**Comment by hrushikesh-s** [comment]
@Zhuoying, only `1 test` is failing here.
```
=========================== short test summary info ============================
FAILED tests/common/schemas/test_cclib.py::test_cclib_taskdoc - KeyError: 'test'
====== 1 failed, 135 passed, 1 skipped, 33 warnings in 424.24s (0:07:04) =======
```

**Comment by Zhuoying** [comment]
@hrushikesh-s Which version of emmet here? 
I suppose before v0.70.0, there were only 1 or 2 errors; after the update to v0.70.0 (fix **entry=None**), there are 32 errors.
Isn't that what we are trying to solve now?

**Comment by hrushikesh-s** [comment]
The CI is installing `emmet-core=0.70.0` in this branch. 
See [here](https://github.com/materialsproject/atomate2/actions/runs/6501378144/job/17658610442?pr=566#step:5:773) for exact details 


> @hrushikesh-s Which version of emmet here? I suppose before v0.70.0, there were only 1 or 2 errors; after the update to v0.70.0 (fix **entry=None**), there are 32 errors. Isn't that what we are trying to solve now?

**Comment by Zhuoying** [comment]
@hrushikesh-s I see why the error numbers are different here and as in #548.
Your base branch is **pydantic2** here while in #548, the base is **main**.

**Comment by Zhuoying** [comment]
Close for it is a duplicate PR.

**Pull request merged**
