### PR TITLE
update lobstertask schema: add bandoverlaps,grosspop and sitepotentials fields

### PR DESCRIPTION
**Pull request by naik-aakash**
## Update Lobstertaskschema

* Added sitepotentials, bandoverlaps, grosspopulations field to schema
* Update associated tests

### CODE REVIEW

**Comment by naik-aakash** [comment]
Hi @JaGeo , it would be great if you can also have a look at it when feasible

**Comment by JaGeo** [comment]
Maybe, you can do a test run on 50 compounds and check if you can recreate all relevant and also the new objects from thr schema 😃.

Then, it's fine from my side.

**Comment by naik-aakash** [comment]
> Maybe, you can do a test run on 50 compounds and check if you can recreate all relevant and also the new objects from thr schema 😃.
> 
> Then, it's fine from my side.

Yes, on it and will update here and let you know when it is done so it can be merged 😄

**Comment by naik-aakash** [comment]
Hi @janosh @utf  , I think this PR is ready to be merged. Can you please review it and if you have any further suggestions, I would be happy to address it

**Comment by JaGeo** [comment]
Hi @utf, @naik-aakash and I would kindly ask you to have a look at this pull request. We are currently working on a resubmission and a merged pull request would help a lot with regard to repoducibility. 
Thank you very much in advance.

**Comment by JaGeo** [comment]
Not sure how the maintainer list works here at the moment. @janosh, In case you are allowed and have some time, we would love a review because of the issues mentioned above.

**Comment by utf** [comment]
Sorry for the delay. This all looks good to me!

**Comment by janosh** [comment]
@JaGeo I only do reviews and merge minor uncontentious-looking PRs (like docs, linting, tests).

**Comment by JaGeo** [comment]
Thanks, @utf !

**Pull request merged**
