### PR TITLE
Update LobsterTaskDoc 

### PR DESCRIPTION
**Pull request by naik-aakash**
# Summary

The changes in the are first step toward LOBSTER dataset available via MP

# Todo

- [x] decouple file pymatgen file parsing and post-processing (lobsterpy)
- [x] Set `save_computational_data_jsons `and `add_coxxcar_to_task_document ` default to false 
- [x] Adapt tests to accommodate the update in defaults
- [x] Move`Bandoverlaps ,Charge, Grosspop, Icohplist, MadelungEnergies, SitePotential` fields to data (Objects could be larger than 16MB for large structure)
- [x] Option to manipulate lobsterpy kwargs
- [x] redefine fields to have minimum redundant information
- [x] Move `Charge`, `MadelungEnergies `back to mongostore (size we suspect will not be larger than 16 MB , as these are simple text files with minimal data in them)
- [x] Nest strongest_bonds fields

### CODE REVIEW

**Comment by naik-aakash** [comment]
Hi @janosh , @utf , any ideas how to fix this issue properly for this pydantic error ?
 https://github.com/materialsproject/atomate2/pull/723/commits/5c88c8fcd04bf4cfc2c2fe8ee7c372c5e32a0c59

**Comment by naik-aakash** [comment]
> Hi @janosh , @utf , any ideas how to fix this issue properly for this pydantic error ? [5c88c8f](https://github.com/materialsproject/atomate2/commit/5c88c8fcd04bf4cfc2c2fe8ee7c372c5e32a0c59)
> 
> Do I need to define again new Models here for all this objects I made `MSONable` in pymatgen? Or simply pass them to datastore ? [materialsproject/pymatgen#3627](https://github.com/materialsproject/pymatgen/pull/3627)

Sorry, nevermind, I think I got the issue. Just a new release of pymatgen should fix it I think. I had installed pymatgen from repo locally and tests passed and I forgot this for a moment 😅

**Comment by naik-aakash** [comment]
Hi @munrojm, can you please have a look at the updated schema? We have now made it possible to turn off the LobsterPy analysis . So this can be used to just parse the outputs. 

Let me know if anything needs to be changed. If it is fine, maybe you can run some tests with it.

**Comment by munrojm** [comment]
@naik-aakash the updated doc with and without analysis still still extremely large when parsed. The one example I have is over 200MB uncompressed for both the former and latter. Looks like large volumetric data still should be factored out in the same way DOS and BS data is done in the other task documents.

**Comment by naik-aakash** [comment]
> @naik-aakash the updated doc with and without analysis still still extremely large when parsed. The one example I have is over 200MB uncompressed for both the former and latter. Looks like large volumetric data still should be factored out in the same way DOS and BS data is done in the other task documents.

Hi @munrojm , Large objects are already factored out to datastore especially generated from Lobster. Am not sure I got what you meant to say. Can you please be more specific?

**Comment by JaGeo** [comment]
@munrojm it might also already help if you let us know which material you tested so that we can run tests ourselves. Thanks!

**Comment by naik-aakash** [comment]
Hi @utf , if you have any specific comments on the changes. Let us know

**Comment by JaGeo** [comment]
@naik-aakash there are some conflicts here

**Pull request merged**
