### PR TITLE
Update minimum `monty` version, allow newer `pydantic`

### PR DESCRIPTION
**Pull request by mkhorton**
Thanks to @gpetretto's [PR in `monty`](https://github.com/materialsvirtuallab/monty/pull/597), it seems like we can allow atomate2 to use the latest pydantic. Thanks to Robert Pinsler for notification.

### CODE REVIEW

**Comment by utf** [comment]
Thanks @mkhorton!

I think @esoteric-ephemera's recent PR to emmet should fix the final test: https://github.com/materialsproject/emmet/pull/937

I've also set up a new issue to track the path to the next atomate2 release here: #721

**Comment by utf** [comment]
Hi @JaGeo and @naik-aakash, updating pymatgen and lobsterpy to the latest versions seems to have broken the phonon and lobster workflows. Are you able to take a look?

**Comment by JaGeo** [comment]
LOBSTER is on our todo. Phonon not yet. Magnetic moments in the PhononAtoms object seem to break the workflow now. I will try.

**Comment by utf** [comment]
Thanks @JaGeo. Downgrading pymatgen seems to work for now. I'll merge this PR and open an issue about the pymatgen version.

**Comment by JaGeo** [comment]
Thanks! We are still working on the MP integration of the Lobster data and this required some changes ...

**Pull request merged**
