### PR TITLE
Add `SevenNetRelaxMaker` + `SevenNetStaticMaker` to force field jobs

### PR DESCRIPTION
**Pull request by janosh**
looks like a new open source SOTA model that beats CHGNet and MACE-MP according to preliminary MBD results. currently reproducing their results (since weights are public 👍) and testing quality of harmonic phonons, hence this PR

https://github.com/janosh/matbench-discovery/pull/112

### CODE REVIEW

**Comment by utf** [comment]
Hi @janosh, do you know how to fix the failing error? This would be great to have in atomate2.

**Comment by janosh** [comment]
yes, the test is straighforward to fix. i wanted to wait on [the PyPI release](https://github.com/MDIL-SNU/SevenNet/issues/52) before merging so we can add `SevenNet` to `pyproject.toml`. but we can also raise an `ImportError` with a link to the [manual install steps](https://github.com/MDIL-SNU/SevenNet?tab=readme-ov-file#installation) if this is time sensitive

**Comment by utf** [comment]
No rush, that makes sense to wait for Pypi. Thanks!

**Comment by janosh** [comment]
this is ready to go except for 1 failing test. i added a new test that checks the `PhononMaker` is initializable in combination with all ML force fields. it's failing for GAP with a very non-descript error message

```
        """
        f90wrap.runtime.FortranDerivedType.__init__(self)
>       result = quippy._quippy.f90wrap_potential_initialise(args_str=args_str, pot1=(None if pot1 is None else pot1._handle), \
            pot2=(None if pot2 is None else pot2._handle), param_str=param_str, bulk_scale=(None if bulk_scale is None else \
            bulk_scale._handle), error=error)
E       RuntimeError

/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/quippy/potential_module.py:241: RuntimeError
```

not sure who would know how to fix this, maybe @JaGeo? we can also skip this test since it's being added in this PR

**Pull request merged**
