### PR TITLE
Update CondensedBondingAnalysis schema

### LINKED ISSUE #468: New LobsterPy release
An argument name was changed in LobsterPy which will break the Lobster workflow schema. We need to adapt this.

@naik-aakash

### PR DESCRIPTION
**Pull request by naik-aakash**
Adapts argument names as per latest LobsterPy release which breaks the Lobster workflow schema

 Closes #468

### CODE REVIEW

**Comment by naik-aakash** [comment]
Hi @utf , this PR is ready to be reviewed and merged

**Comment by JaGeo** [comment]
@naik-aakash , could you change the requirements in the lobster part as well? >=0.3.0?

**Comment by naik-aakash** [comment]
> @naik-aakash , could you change the requirements in the lobster part as well? >=0.3.0?

Done 😃

**Comment by utf** [comment]
Great, thanks!

**Pull request merged**
