### PR TITLE
Reduce test times with Codecov CLI

### PR DESCRIPTION
**Pull request by thomasrockhu-codecov**
## Summary

Hi, Tom from [Codecov](https://about.codecov.com) here. We are beta-testing a new feature called Automated Test Selection (ATS), and this repository looked like a viable candidate. ATS uses code coverage to select the appropriate tests to run based on new code changes. The current implementation is fairly conservative and will run a tests as opposed to skipping it.

I ran some tests on a fork of this repository [here](https://github.com/thomasrockhu-codecov/atomate2) and the results can be seen in the chart below. What we gathered is that there are significant decreases to CI time. In the worst case, it adds about a minute and a half of overhead to your CI times. 

Generally, _**it reduces test times from 10 min to < 1 min**_. The majority of CI time afterwards is in installing dependencies.

If you are willing, I'd love to get your feedback however you're most comfortable (call, email, on this PR). 

<google-sheets-html-origin><style type="text/css"></style>

Commit message | Link to run | ATS runtime (in min) | Original runtime (in min) | Difference (in min) | % Change | ATS test runtime (in min) | Original test runtime (in min) | Difference (in min) | % Change
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
  | [link](https://github.com/thomasrockhu-codecov/atomate2/actions/runs/5515686825) | 21.63 | 20.04 | -1.59 | -7.93% | 10.13 | 11.08 | 0.95 | 8.58%
initial commit | [link](https://github.com/thomasrockhu-codecov/atomate2/actions/runs/5521366805) | 6.83 | 16.89 | 10.06 | 59.56% | 0.83 | 11.32 | 10.49 | 92.69%
add m3gnet static maker + other misc changes | [link](https://github.com/thomasrockhu-codecov/atomate2/actions/runs/5522212488) | 14.94 | 16.28 | 1.34 | 8.23% | 8.96 | 10.83 | 1.87 | 17.29%
combine m3gnet and chgnet TaskDocument function into one | [link](https://github.com/thomasrockhu-codecov/atomate2/actions/runs/5522591984) | 6.51 | 15.98 | 9.47 | 59.26% | 0.44 | 10.86 | 10.42 | 95.96%
add tests for M3GNetRelaxMaker and M3GNetStaticMaker | [link](https://github.com/thomasrockhu-codecov/atomate2/actions/runs/5522773000) | — | — | -- | -- | -- | -- | -- | --
update pyproject.toml + fix: remove pinning of codecov-cli | [link](https://github.com/thomasrockhu-codecov/atomate2/actions/runs/5701842157) | 10.71 | 18.86 | 8.15 | 43.21% | 0.61 | 10.57 | 9.96 | 94.22%
-- | [link](--) | -- | -- | -- | -- | -- | -- | -- | --
Bump myst-parser from 1.0.0 to 2.0.0 (#393) | [link](https://github.com/thomasrockhu-codecov/atomate2/actions/runs/5702041410) | 6.45 | 17.81 | 11.36 | 63.79% | 0.34 | 11.65 | 11.31 | 97.09%
Bump emmet-core from 0.55.5 to 0.57.1 (#392) | [link](https://github.com/thomasrockhu-codecov/atomate2/actions/runs/5702128612) | 6.44 | 18.14 | 11.71 | 64.51% | 0.33 | 12.11 | 11.78 | 97.25%
Bump custodian from 2023.5.12 to 2023.6.5 (#387) | [link](https://github.com/thomasrockhu-codecov/atomate2/actions/runs/5702228110) | 6.77 | 15.41 | 8.64 | 56.06% | 0.36 | 9.83 | 9.47 | 96.38%
clean up doc, remove left-overs from amset example | [link](https://github.com/thomasrockhu-codecov/atomate2/actions/runs/5703399319) | 5.51 | 16.26 | 10.75 | 66.11% | 0.34 | 10.66 | 10.31 | 96.77%

## Additional dependencies introduced (if any)

* [codecov-cli](https://pypi.org/project/codecov-cli/)

## TODO (if any)

- Add `CODECOV_TOKEN` and `CODECOV_STATIC_TOKEN` to repository secrets from [Codecov](https://app.codecov.io/gh/materialsproject/atomate2/settings)

## Checklist

Work-in-progress pull requests are encouraged, but please put [WIP] in the pull request
title.

Before a pull request can be merged, the following items must be checked:

* [x] Code is in the [standard Python style](https://www.python.org/dev/peps/pep-0008/).
  The easiest way to handle this is to run the following in the **correct sequence** on
  your local machine. Start with running [black](https://black.readthedocs.io/en/stable/index.html) on your new code. This will
  automatically reformat your code to PEP8 conventions and removes most issues. Then run
  [ruff](https://ruff.rs).
* [x] Docstrings have been added in the [Numpy docstring format](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_numpy.html).
  Run [ruff](https://beta.ruff.rs/docs/rules/#pydocstyle-d) on your code.
* [ ] Type annotations are **highly** encouraged. Run [mypy](http://mypy-lang.org) to
  type check your code.
* [x] Tests have been added for any new functionality or bug fixes.
* [x] All linting and tests pass.

Note that the CI system will run all the above checks. But it will be much more
efficient if you already fix most errors prior to submitting the PR. It is highly
recommended that you use the pre-commit hook provided in the repository. Simply run
`pre-commit install` and a check will be run prior to allowing commits.

### CODE REVIEW

**Comment by utf** [comment]
Hi @thomasrockhu-codecov thanks for getting in touch.

@janosh do you have any thoughts on this?

**Comment by janosh** [comment]
Looks nice! I'm curious when ATS entered beta and when it's expected to exit.

Also, can this be made to work with [`pytest-split`](https://github.com/jerry-git/pytest-split)? Asking for https://github.com/materialsproject/pymatgen where this could make a lot of sense. But we have occasional PRs that affect enough parts of the code base that tests would time out when running in a single job.

**Comment by janosh** [comment]
> Given that, would you be open to merging this in and seeing if you get similar benefits in CI time?

I'm open, yes.

> Right now, pytest arguments are handled in a codecov.yml configuration. I think we will need to accept arguments in the CLI instead.

Has this been addressed in the meantime?

**Comment by utf** [comment]
I'm going to close this due to inactivity. If there are any updates, feel free to reopen.

**Pull request closed without merging**
