### PR TITLE
[WIP] Support general ASE Calculator for general MLIP MD simulations

### PR DESCRIPTION
**Pull request by chiang-yuan**
## Summary

Given that some of the popular MLIPs lean on ASE Calculator, this PR aims to add ASE Calculator support for MD simulations in a similar manner to #134 and #489. The design is similar to existing [forcefield](https://github.com/materialsproject/atomate2/tree/main/src/atomate2/forcefields) but allows user to pass any subclass of ASE Calculator and run various of dynamics supported by [ASE MD module](https://wiki.fysik.dtu.dk/ase/ase/md.html). 

The design should be kept general and abstract so that we can avoid code duplication and won't need to add more ASE-based MLIPs in the future. This actually makes more sense than the [existing relaxation implementation](https://github.com/materialsproject/atomate2/blob/main/src/atomate2/forcefields/jobs.py) where most of them run ASE calculator as [Relaxer](https://github.com/materialsproject/atomate2/blob/e2181ea87f8e51f6362369d61b9c46b29e4d392a/src/atomate2/forcefields/utils.py#L129) at the bottom level. By doing so we can also ensure that all the MLIPs fairly run on the same settings of dynamics .

## TODO
- [x] Add support for temperature and pressure schedules (T/P ramp, non-linear temperature schedule, shear external pressure, etc.)
- [ ] For NPT ensemble, add `mask` and `dyn.set_fraction_traceless(0)`
- [ ] Custodian and `ASEJob`
- [ ] MultiMDMaker
- [ ] test

## Checklist

Work-in-progress pull requests are encouraged, but please put [WIP] in the pull request
title.

Before a pull request can be merged, the following items must be checked:

* [ ] Code is in the [standard Python style](https://www.python.org/dev/peps/pep-0008/).
  The easiest way to handle this is to run the following in the **correct sequence** on
  your local machine. Start with running [`ruff`](https://docs.astral.sh/ruff) and `ruff format` on your new code. This will
  automatically reformat your code to PEP8 conventions and fix many linting issues.
* [ ] Doc strings have been added in the [Numpy docstring format](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_numpy.html).
  Run [ruff](https://beta.ruff.rs/docs/rules/#pydocstyle-d) on your code.
* [ ] Type annotations are **highly** encouraged. Run [mypy](http://mypy-lang.org) to
  type check your code.
* [ ] Tests have been added for any new functionality or bug fixes.
* [ ] All linting and tests pass.

Note that the CI system will run all the above checks. But it will be much more
efficient if you already fix most errors prior to submitting the PR. It is highly
recommended that you use the pre-commit hook provided in the repository. Simply run
`pre-commit install` and a check will be run prior to allowing commits.

### CODE REVIEW

**Comment by JaGeo** [comment]
I just want to mention this pull request here  #722 as it is very much related.

**Comment by chiang-yuan** [comment]
Duplicate of #722

**Comment by utf** [comment]
@chiang-yuan are you able to look at https://github.com/materialsproject/atomate2/pull/722 and let me know if this PR captures everything you wanted to achieve here?

If so, can this be closed?

**Comment by chiang-yuan** [comment]
@utf  yes I have added the code in #722 instead of this one, so this could be closed

**Pull request closed without merging**
