### PR TITLE
[WIP] Fix phonon + Lobster flow

### LINKED ISSUE #739: New pymatgen breaks lobster and phonopy workflows
Updating pymatgen and lobsterpy to the latest versions breaks the phonon and lobster workflows.

### PR DESCRIPTION
**Pull request by naik-aakash**
## Changes

1. Update pymatgen, mp-api and Lobsterpy version
2. Add checks to remove magmom from structure to avoid phonopy failures

Closes #739

### CODE REVIEW

**Comment by naik-aakash** [comment]
Hi @JaGeo  and @utf , this changes should in principle fix the phonon workflow once mp-api is compatible with the latest pymatgen version.

Tests fail due to dependencies conflicts

**Comment by naik-aakash** [comment]
Hi @utf and @JaGeo , this PR could be merged now if there are no comments on it :smile:

**Comment by JaGeo** [comment]
@naik-aakash I am not sure removing the initial magnetic moments in all cases is a good solution. We should rather disenable the seekpath option implemented in Phonopy in that case.

**Comment by JaGeo** [comment]
Here is a discussion about it: https://github.com/materialsproject/pymatgen/pull/3555

**Comment by naik-aakash** [comment]
> Here is a discussion about it: [materialsproject/pymatgen#3555](https://github.com/materialsproject/pymatgen/pull/3555)

Ohh, ok, I see. I will check it. Thanks! 😃

**Comment by JaGeo** [comment]
Easy solution for now: removing all magnetic moments and adding a warning that we currently do not consider the initial magnetic structure for determining the symmetry and adding this clearly in the documentation.

**Comment by utf** [comment]
> Easy solution for now: removing all magnetic moments and adding a warning that we currently do not consider the initial magnetic structure for determining the symmetry and adding this also clearly in the documentation.

Yes, this is a good solution.

**Comment by naik-aakash** [comment]
Thanks @utf and @JaGeo , I will now add a warning and also update this in documentation of phonon workflow.

**Comment by JaGeo** [comment]
Tagging @JonathanSchmidt1 in case he might want to contribute to atomate2 with his implementation of a magnetic phonon workflow in a follow-up PR.

**Review by JaGeo — APPROVED** [review]

**Comment by JonathanSchmidt1** [comment]
It might take a few weeks till I find the time but I would be happy to add it.
It will just not have the full functionality of the normal phonon workflow as
PRIMITIVE_AXES = auto and BAND = auto are not allowed with MAGMOM in phonopy.

**Comment by JaGeo** [comment]
@JonathanSchmidt1 Great. Yes, sure. I have mentioned some suggestions above as well

**Comment by utf** [comment]
Thanks @naik-aakash  and @JaGeo

**Pull request merged**
