### PR TITLE
Add clearer documentation on lobster worker

### PR DESCRIPTION
**Pull request by JaGeo**
I added more specific documentation for the Lobster worker. It should now be quite easy to experienced fireworks users to adapt to the Lobster workflow.

As this is a tiny change: 
@janosh or @utf

Thanks!

### CODE REVIEW

**Comment by JaGeo** [comment]
This would be ready foe review as well.

**Comment by janosh** [comment]
Thanks @JaGeo!

**Comment by JaGeo** [comment]
Thanks, @janosh . A tiny issue in the linting was somehow introduced. Tests on main are now failing, I think.

**Comment by janosh** [comment]
No worries, fixed in 24eaac41.

**Pull request merged**
