### PR TITLE
[FIX] Fix major bug that caused `user_incar_settings` to be overwritten in some cases

### PR DESCRIPTION
**Pull request by matthewkuner**
## Summary

Fixes major bug that caused `user_incar_settings` to be overwritten in some cases.

### CODE REVIEW

**Comment by matthewkuner** [comment]
@utf Let me know your thoughts on setting `auto_ismear` to `False`, as this will affect whether or not I have to change the tests. Otherwise, this is ready to be merged.

**Comment by utf** [comment]
Sorry for the late response. There is an issue with just applying user_incar_settings again at the end. That's because some settings like MAGMOM/LDAUU etc are set using a dictionary in the user_incar_settings. These are then parsed by the input set generator and converted into the format required by VASP. 

So I think we'll have to do it the way I mentioned in the GitHub issue.

**Comment by matthewkuner** [comment]
@utf no problem. And what are your thoughts regarding having `auto_ismear` as False?

**Comment by utf** [comment]
Personally, I think we can leave it to `True` just for consistency. But maybe @jmmshn has an opinion since he implemented this change.

**Comment by matthewkuner** [comment]
@jmmshn Honestly I am getting a bit lost with how to fix the failing tests for ISMEAR. Can you help me with this?

**Comment by jmmshn** [comment]
Hi @matthewkuner  I can only recall implementing `auto_lreal` I think `auto_ismear` was done with the major update to the VASP settings earlier this year.

As far as fixing the failing tests it just looks like you have changed settings to the incars are now different.
 I think you have three options:
1. Rerun the tests with the updated settings
2. Edit the inputs and outputs manually (INCAR, OUTCAR, (maybe) vasprun.xml) but this will might create inconsistencies in parsing.
3. Mock only a small part of the test to avoid this problem.

I would start with (2), see how intrusive the change becomes, and then make decisions from there.

**Comment by utf** [comment]
If you go for point 2, you only need to edit the input INCAR (not any of the outputs).

**Comment by matthewkuner** [comment]
@utf could this be related to https://github.com/materialsproject/custodian/pull/271 ?

**Comment by matthewkuner** [comment]
@jmmshn is there any chance you could help figure out what is going wrong here? I'm honestly lost w.r.t. understanding the mock vasp / whether the files should be changed or if it was a change in the input set behavior (as mentioned by @utf) / etc.

**Comment by matthewkuner** [comment]
@utf 

> This looks like the behaviour of the input set has changed?

The relevant files in the MPInputSets haven't changed in months. Do you mean the Atomate2 sets?

**Comment by matthewkuner** [comment]
@jmmshn Could this have to do with the changes made to `_set_kspacing` in your #270 ?

**Comment by jmmshn** [comment]
@matthewkuner OK I can help.  There are some weird stuff breaking for me as well so it will make sense to have a chat.
Let's coordinate offline.

**Comment by utf** [comment]
Ok, this seems fixed now. @matthewkuner would you be able to add an extra test for the previous behaviour that was broken?

**Comment by matthewkuner** [comment]
@utf it looks like the `auto_updates` is never actually applied to the incar now, though, no?

**Comment by matthewkuner** [comment]
@utf tests have been added. Let me know if they are adequate--if so, this should be ready for merging.

**Comment by utf** [comment]
Great, thank you!

**Pull request merged**
