### PR TITLE
 Simplify phonon `get_supercell_size()` and test clean up

### PR DESCRIPTION
**Pull request by janosh**
- include method (`vasp`|`force_field`) in `PhononMaker` test names
- simplify phonon `get_supercell_size()` job
- better use `pytest` structure fixtures to reduce duplication

### CODE REVIEW

**Comment by janosh** [comment]
waiting on `uv` release https://github.com/astral-sh/uv/issues/313#issuecomment-2014268571

**Comment by janosh** [comment]
looks like we can successfully migrate CI deps installation to `uv`. @utf are you ok with this? should give a decent speed up as in https://github.com/materialsproject/pymatgen/pull/3675#issuecomment-1983033505

**Comment by janosh** [comment]
`uv` install time is ~40s vs [`pip`'s ~150s](https://github.com/materialsproject/atomate2/actions/runs/8397746376/job/23001572012), so a 3.7x speed up

**Comment by janosh** [comment]
looks like the test failures could be related to recent `jsanitize` changes in https://github.com/materialsvirtuallab/monty/pull/638. @Andrew-S-Rosen do you happen to know a good fix here?

**Comment by Andrew-S-Rosen** [comment]
@janosh: I must admit, I can't see how that PR would cause the issue here. The command being called here is `jsanitize(obj, strict=True, allow_bson=True)`, but the logic I added only kicks in if `recursive_msonable=True` (which is not the case by default). I also don't think replacing an `isinstance()` check with `try`/`except` would trigger this error in particular. That said, the timing is suspicious. 😅  There was also https://github.com/materialsproject/maggma/pull/930 in maggma, but that doesn't seem to be called here. 

Might help if we knew which dependencies changed. Is there not a `requirements.txt` file with pinned versions used in CI?

**Comment by JaGeo** [comment]
I think we already talked about a similar issue here ( #781 , not the CHGNet issue but the one of the band structure workflow). I think emmet was at fault.

**Comment by JaGeo** [comment]
See https://github.com/materialsproject/atomate2/issues/781#issuecomment-2007490186

**Comment by janosh** [comment]
@Andrew-S-Rosen my bad, should have looked more closely at the stack trace. was going mostly by temporal correlation 😅 

@JaGeo thanks for the pointer! i missed that discussion 🙏

**Pull request merged**
