### PR TITLE
fix CP2K TaskDocument

### PR DESCRIPTION
**Pull request by lory-w**
## Summary

This PR addresses the ValidationError occurring in the TaskDocument schema due to improper handling of the cp2k_input and locpot fields. This issue is documented in issue #899 

* Changed `cp2k_input` in CalculationInput to be a union of `CP2KInput` object and dict to accommodate different possible types for cp2k_input
* Changed `locpot` in CalculationOutput to be an optional field

### CODE REVIEW

**Comment by JaGeo** [comment]
@lory-w thank you! Is there a chance that you could add a test as well?

**Comment by lory-w** [comment]
Hi, 
Thank you for reviewing the PR. I attempted to write a pytest but the error only occurs when the calculation results are queried by Jobflow from Store (in my case mongodb). However, the current test suite in the repo does not seem to have integration with mongodb, so I cannot reproduce the bug within the unit tests.

Would you suggest any specific approach to handle this? Thanks!

**Comment by JaGeo** [comment]
@utf maybe you could have a look once you have time!

**Comment by utf** [comment]
I will look into the jobflow issue but will merge this for the time being.

**Pull request merged**
