### PR TITLE
Tutorial for blob storage with test

### PR DESCRIPTION
**Pull request by jmmshn**
## Tutorial for blob storage with test

* Added tutorial for `store_volumetric_data`
* Added a way for notebooks to be tested.

## Additional dependencies introduced (if any)

`nbmake` to make testing possible.

### CODE REVIEW

**Comment by jmmshn** [comment]
@utf let me know if this change looks OK, I can start writing the other tutorials.

**Comment by JaGeo** [comment]
@jmmshn I am really excited about integrating such tutorials once this is merged. Especially for the phonon workflow, this is straightforward.

**Comment by utf** [comment]
Thanks @jmmshn this looks great.

**Comment by JaGeo** [comment]
@utf shouldn't this tutorial be somehow connected to the documentation? I am a bit confused where to put new tutorials. We would like to migrate our tutorial on the phonon workflows to atomate2.

**Pull request merged**
