### PR TITLE
Fix bump phonopy

### PR DESCRIPTION
**Pull request by naik-aakash**
# Changes

1. Update phonopy version
2. Switch off the Gruneisen parameter computations at gamma point following (https://github.com/phonopy/phonopy/issues/455#issuecomment-2495156556)

# Todo

- [x] Investigate what cause the change in gruneisen parameter value leading to failure in test
- [x] Fix failing phonon workflow with using latest phonopy version (v2.30.1)

### CODE REVIEW

**Comment by JaGeo** [comment]
How large are the changes? Could you give more details? Thanks!

**Comment by naik-aakash** [comment]
The average Gruneisen value now comes out to be  `1.271535057337552` using v2.28 (using v2.27 we used to get `1.1882292157682082`)

**Comment by JaGeo** [comment]
Yeah, I think we need a bit more analysis here. This is quite a large change

**Comment by naik-aakash** [comment]
The latest version of phonopy causes phonon workflow test to also fail (cause of failure seems to originate from force constants computation default being changed)

**Comment by JaGeo** [comment]
I would need more details to act. E.g., How large is the change? Why does this only affect the Grüneisen parameter workflow? What is different?

We can do this privately if you prefer.

**Comment by naik-aakash** [comment]
> I would need more details to act. E.g., How large is the change? Why does this only affect the Grüneisen parameter workflow? What is different?
> 
> We can do this privately if you prefer.

As I have mentioned above, now with latest version phonon workflow test is also affected. I will try to share the details in next days

**Comment by JaGeo** [comment]
@naik-aakash one last question: do you need all test files still or can one set be removed?

**Comment by naik-aakash** [comment]
> @naik-aakash one last question: do you need all test files still or can one set be removed?

Hi @JaGeo, Thanks for spotting this. I Have now removed the test files that are no longer used

**Comment by JaGeo** [comment]
@naik-aakash thanks. This looks good. I will merge.

**Comment by JaGeo** [comment]
For everyone else seeing this and wondering why we are changing tests:

By accident, one of the phonon tests used wrong test files. This only appeared as a problem when phonopy added more strict handling of the forces. 

The Grüneisen parameter computation was also affected by a phonopy change. However, as this mostly affected an unrealiable value at gamma, we simply remove it from the mesh computation. We should have likely done this already before.

**Pull request merged**
