### PR TITLE
Minor docs cleanup

### PR DESCRIPTION
**Pull request by esoteric-ephemera**
Correcting out of date info / incorrect links in the docs:
- Should close [#1043](https://github.com/materialsproject/atomate2/issues/1043), wherein the [VASP workflows](https://materialsproject.github.io/atomate2/user/codes/vasp.html#list-of-vasp-workflows) link to makers in other code bases 
- Some out of date OpenMM info - @orionarcher  can you double check my changes are right? The docs were pointing to your branch for install info

### CODE REVIEW

**Comment by JaGeo** [comment]
@esoteric-ephemera Thank you very much! 😀

**Comment by JaGeo** [comment]
Waiting for @orionarcher to confirm before merging.

**Comment by orionarcher** [comment]
LGTM

**Review by janosh — APPROVED** [review]
thanks @esoteric-ephemera! 👍

**Pull request merged**
