### PR TITLE
Ensure MP VASP sets don't use auto_ismear, few other fixes

### PR DESCRIPTION
**Pull request by esoteric-ephemera**
In response to issue [#672](https://github.com/materialsproject/atomate2/issues/672), all MP VASP input sets now set `auto_ismear = False` by default. This change leads to the following behavior:
- GGA workflow ***always*** uses tetrahedron smearing (ISMEAR = -5, SIGMA = 0.05). This is consistent with the atomate GGA workflow and left for consistency
- meta-GGA workflow uses Gaussian smearing (ISMEAR = 0, SIGMA = 0.05) for relaxations and tetrahedron smearing (ISMEAR = -5, SIGMA = 0.05) for the final static. This is not quite the behavior from the atomate workflow, but is a minor change given that the atomate wf didn't include a static or CHG/WAVECAR initialization like the atomate2 one does
- The meta-GGA workflow behavior is consistent with the wf structure moving forwards with MP
- Updated test files to reflect these changes

Few other fixes/improvements:
- Removed dependence on `pkg_resources.resource_filename` as this has been deprecated in favor of `importlib.resources.files`
- Froze the MACE model used in the elastic forcefield workflow ***test*** - I saw that the test could fail ([link](https://github.com/materialsproject/atomate2/actions/runs/7474432469/job/20340565788)) when the model couldn't be downloaded on the fly

### CODE REVIEW

**Comment by mkhorton** [comment]
Asking to clarify: is this issue in relation to the MP GGA (PBE) workflow, or the MP GGA (PBEsol) workflow used to bootstrap the R2SCAN calculation?

If the former, I thought the historical behaviour was to use Gaussian smearing (ISMEAR=0) as a sensible default for relaxations, and tetrahedron only for statics?

**Comment by esoteric-ephemera** [comment]
It ends up being both workflows (not just the PBEsol pre-relax) because the value of ISMEAR changes according to bandgap. We don't necessarily want Methfessel-Paxton smearing in case a system is incorrectly predicted to be a metal in the GGA pre-relax. 

> If the former, I thought the historical behaviour was to use Gaussian smearing (ISMEAR=0) as a sensible default for relaxations, and tetrahedron only for statics?

I recall looking into the atomate workflows and finding that that the `OptimizeFW` defaults to `MPRelaxSet` with no further changes to ISMEAR. That ends up giving `ISMEAR = -5` in relaxations. 

I've also done some sanity checks against the MP task docs, and it looks like `ISMEAR = -5` was always used in GGA relaxations.

**Comment by utf** [comment]
Thanks @esoteric-ephemera. Can I just ask about the motivation for disabling `auto_ismear` - is that for consistency with atomate1/pymatgen input sets or is there another reason?

**Comment by esoteric-ephemera** [comment]
Hey @utf, for the GGA workflow, it's consistency with atomate. To be consistent with atomate, the meta-GGA workflow would have to start with Methfessel-Paxton smearing (ISMEAR = 2, SIGMA = 0.2) and then switch to tetrahedron (ISMEAR = -5, SIGMA = 0.05) if the gap in the PBEsol step is nonzero

I will say I'm in the process of running the "new" (updated pseudopotentials, parameters and hopefully +U's) workflows for both meta-/GGA workflows. So if we'd rather have these exist just as their atomate 1 equivalents, I'm happy to make that change

**Comment by utf** [comment]
Understood! I think this is ok for now. Thanks very much.

**Comment by mkhorton** [comment]
Thanks @esoteric-ephemera, not the first time my memory has been incorrect :)

**Comment by Andrew-S-Rosen** [comment]
FYI, the MACE model downloading issue is fixed in `main` of the MACE repo.

**Comment by Andrew-S-Rosen** [comment]
@esoteric-ephemera --- with this change, is ISMEAR always equal to 0 and SIGMA always equal to 0.05 in the MP meta-GGA relax and pre-relax steps (unless changed by Custodian)? I'm not opposed -- I just want to make sure I'm understanding this correctly.

**Comment by esoteric-ephemera** [comment]
Yeah for the pre-relaxation , ISMEAR = 0 and SIGMA = 0.05. The r2SCAN relax continues with 0.22 (metal) <= SIGMA <= 0.44 (wide-gap insulator) and ISMEAR = 0. The final r2SCAN static uses ISMEAR = -5.

This is mostly to avoid situations where Methfessel-Paxton (ISMEAR > 0) smearing is used to relax insulators, or tetrahedron (ISMEAR = -5) method is used to relax metals. The atomate 1 r2SCAN flow had the former problem, the PBE flow has the latter problem

**Comment by Andrew-S-Rosen** [comment]
Thanks!! For clarification: presumably you meant KSPACING instead of SIGMA for the 0.22 to 0.44 comment.

**Comment by esoteric-ephemera** [comment]
Whoops yes thanks! Corrected above

**Pull request merged**
